services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgresql://postgres:password@:5432/mydb


  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local

